Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/03/2019
Var

area: real
base: real
altura: real

Inicio
escreva ( " Digite o valor da base: ")
leia(base)
escreva ( " Digite o valor da altura: ")
leia(altura)
area:= (( base * altura) / 2))
escreva ( " O valor da área do triângulo será: ", area)

Fimalgoritmo